import type { NodeSettings } from './types';

/** A serialized snapshot of a parent layer's settings + every sublayer's settings.
 *  Presets describe geometry + which palette slots each element references — the colors
 *  themselves come from the active theme (src/themes.ts). */
export interface Preset {
  name: string;
  nodeSettings: NodeSettings;
  nodeSubLayers: Array<{ settings: NodeSettings }>;
  /** Render-stack position of the parent layer (0 = bottom, default). Sublayers stack
   *  in array order around it. */
  parentStackIndex?: number;
}

/** Curated presets users can pick from the top of the Properties pane. The image source
 *  (`nodeSource`) is intentionally not part of a preset so the same look can be applied
 *  to any input photo. */
export const BUNDLED_PRESETS: Preset[] = [
  {
    name: 'Stipple flow',
    nodeSettings: {
      density: 4250,
      thresholdRange: { min: 0, max: 45 },
      gamma: 1.3,
      dotScale: 2.5,
      lineScale: 1,
      distance: 3,
      grid: true,
      routing: 'strict',
      dirAngle: 16,
      dirSpread: 30,
      traceBranch: 3,
      fill: false,
      dotOutline: false,
      dotOutlineWidth: 0.25,
      dotColorKey: 'color9',
      lineColorKey: 'color9',
      // Sparse accent dots from the Figma theme frames: a light pop and a contrast pop.
      // Full-range thresholds so every sampled dot is eligible regardless of the layer band.
      nuances: [
        { id: 'stipple-hl-light', colorKey: 'color1', amount: 0.02, thresholdRange: { min: 0, max: 255 }, seed: 11 },
        { id: 'stipple-hl-pop', colorKey: 'color2', amount: 0.035, thresholdRange: { min: 0, max: 255 }, seed: 23 },
      ],
      seed: 0,
      imageOffsetX: 0,
      imageOffsetY: 0,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 3450,
          thresholdRange: { min: 78, max: 99 },
          gamma: 1.15,
          dotScale: 0.9,
          lineScale: 1.3,
          distance: 14.6,
          grid: false,
          routing: 'flow',
          dirAngle: 145,
          dirSpread: 127,
          traceBranch: 6,
          fill: false,
          dotOutline: false,
          dotOutlineWidth: 0.75,
          dotColorKey: 'color4',
          lineColorKey: 'color3',
          seed: 304,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
  },
  {
    // Exported from the app (node-preset-1781203277482): filled traces with outlined dots
    // over a bright band, above a coarse grid-trace band. Parent renders above the sublayer.
    name: 'Sparse traces',
    nodeSettings: {
      density: 800,
      thresholdRange: { min: 153, max: 255 },
      gamma: 0.45,
      dotScale: 1.05,
      lineScale: 2.5,
      distance: 15,
      grid: false,
      routing: 'traces',
      dirAngle: 145,
      dirSpread: 65,
      traceBranch: 7,
      fill: true,
      dotOutline: true,
      dotOutlineWidth: 0.7,
      dotColorKey: 'color9',
      lineColorKey: 'color7',
      nuances: [
        { id: 'sparse-hl-light', colorKey: 'color1', amount: 0.03, thresholdRange: { min: 0, max: 255 }, seed: 7 },
        { id: 'sparse-hl-pop', colorKey: 'color2', amount: 0.04, thresholdRange: { min: 0, max: 255 }, seed: 19 },
      ],
      seed: 0,
      imageOffsetX: 0,
      imageOffsetY: 0,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 1150,
          thresholdRange: { min: 50, max: 175 },
          gamma: 0.3,
          dotScale: 4,
          lineScale: 2.8,
          distance: 0,
          grid: true,
          routing: 'traces',
          dirAngle: 227,
          dirSpread: 108,
          traceBranch: 5,
          fill: false,
          dotOutline: false,
          dotOutlineWidth: 0.75,
          dotColorKey: 'color2',
          lineColorKey: 'color3',
          nuances: [],
          seed: 309,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
    parentStackIndex: 1,
  },
  {
    name: 'Grid flow',
    nodeSettings: {
      density: 950,
      thresholdRange: { min: 0, max: 58 },
      gamma: 1.25,
      dotScale: 1.45,
      lineScale: 1,
      distance: 17.4,
      grid: true,
      routing: 'strict',
      dirAngle: 106,
      dirSpread: 110,
      traceBranch: 8,
      fill: false,
      dotOutline: false,
      dotOutlineWidth: 0.25,
      dotColorKey: 'color1',
      lineColorKey: 'color7',
      // Parent dots are already the light slot, so highlights pull from the contrast
      // pop and the grid-accent slot instead.
      nuances: [
        { id: 'grid-hl-pop', colorKey: 'color2', amount: 0.03, thresholdRange: { min: 0, max: 255 }, seed: 5 },
        { id: 'grid-hl-accent', colorKey: 'color8', amount: 0.02, thresholdRange: { min: 0, max: 255 }, seed: 13 },
      ],
      seed: 0,
      imageOffsetX: 0,
      imageOffsetY: 0,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 3350,
          thresholdRange: { min: 78, max: 189 },
          gamma: 1.15,
          dotScale: 1.25,
          lineScale: 4,
          distance: 7.8,
          grid: true,
          routing: 'flow',
          dirAngle: 90,
          dirSpread: 61,
          traceBranch: 4,
          fill: false,
          dotOutline: false,
          dotOutlineWidth: 0.75,
          dotColorKey: 'color8',
          lineColorKey: 'color7',
          seed: 445,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
  },
  {
    // Exported from the app (node-preset-1781202877330): grid traces with a strong light
    // highlight, under a directional outlined-dot band. Parent renders above the sublayer.
    name: 'Trace weave',
    nodeSettings: {
      density: 1900,
      thresholdRange: { min: 0, max: 138 },
      gamma: 0.9,
      dotScale: 0.95,
      lineScale: 2.75,
      distance: 10.3,
      grid: true,
      routing: 'traces',
      dirAngle: 211,
      dirSpread: 48,
      traceBranch: 4,
      fill: false,
      dotOutline: false,
      dotOutlineWidth: 0.25,
      dotColorKey: 'color9',
      lineColorKey: 'color7',
      nuances: [
        { id: 'weave-hl-light', colorKey: 'color1', amount: 0.075, thresholdRange: { min: 0, max: 255 }, seed: 7 },
        { id: 'weave-hl-pop', colorKey: 'color2', amount: 0.035, thresholdRange: { min: 0, max: 255 }, seed: 19 },
      ],
      seed: 0,
      imageOffsetX: 0,
      imageOffsetY: 0,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 1750,
          thresholdRange: { min: 77, max: 176 },
          gamma: 2.6,
          dotScale: 1.15,
          lineScale: 2,
          distance: 11.6,
          grid: true,
          routing: 'directional',
          dirAngle: 227,
          dirSpread: 108,
          traceBranch: 4,
          fill: false,
          dotOutline: true,
          dotOutlineWidth: 0.7,
          dotColorKey: 'color2',
          lineColorKey: 'color3',
          nuances: [],
          seed: 582,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
    parentStackIndex: 1,
  },
  {
    // Exported from the app (node-preset-1782384943935): free-routed grid dots with a deep
    // dot nuance over a filled strict-grid band with outlined dots and warm dot/line
    // nuances. Parent renders below the sublayer.
    name: 'Mosaic',
    nodeSettings: {
      density: 1750,
      thresholdRange: { min: 0, max: 67 },
      gamma: 1.2,
      dotScale: 2.6,
      lineScale: 2.8,
      distance: 2.6,
      grid: true,
      routing: 'free',
      dirAngle: 211,
      dirSpread: 48,
      traceBranch: 4,
      fill: false,
      dotOutline: false,
      dotOutlineWidth: 0.25,
      dotColorKey: 'color9',
      lineColorKey: 'color7',
      nuances: [
        { id: 'mosaic-dots-deep', target: 'dots', colorKey: 'color9', amount: 0.032598195834544194, thresholdRange: { min: 166, max: 233 }, seed: 489 },
      ],
      seed: 620,
      imageOffsetX: 0,
      imageOffsetY: -0.16920002527757688,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 1700,
          thresholdRange: { min: 77, max: 171 },
          gamma: 2.45,
          dotScale: 1.1,
          lineScale: 1.25,
          distance: 6.7,
          grid: true,
          routing: 'strict',
          dirAngle: 227,
          dirSpread: 62,
          traceBranch: 6,
          fill: true,
          dotOutline: true,
          dotOutlineWidth: 0.7,
          dotColorKey: 'color2',
          lineColorKey: 'color3',
          nuances: [
            { id: 'mosaic-sub-warm', target: 'dots', colorKey: 'color4', amount: 0.13804330162022996, thresholdRange: { min: 24, max: 192 }, seed: 546 },
            { id: 'mosaic-sub-line-dark', target: 'lines', colorKey: 'color9', amount: 0.1126967734741715, thresholdRange: { min: 99, max: 245 }, seed: 430 },
            { id: 'mosaic-sub-line-accent', target: 'lines', colorKey: 'color8', amount: 0.12902143051109283, thresholdRange: { min: 0, max: 255 }, seed: 825 },
          ],
          seed: 440,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
    parentStackIndex: 0,
  },
  {
    // Exported from the app (node-preset-1782382262784): dense strict-grid stipple with
    // warm dot/line nuances over a coarse trace band of big outlined dots. Parent renders
    // above the sublayer.
    name: 'Ember grid',
    nodeSettings: {
      density: 2500,
      thresholdRange: { min: 145, max: 255 },
      gamma: 0.55,
      dotScale: 0.85,
      lineScale: 1.25,
      distance: 11.1,
      grid: true,
      routing: 'strict',
      dirAngle: 145,
      dirSpread: 65,
      traceBranch: 7,
      fill: false,
      dotOutline: false,
      dotOutlineWidth: 0.55,
      dotColorKey: 'color9',
      lineColorKey: 'color7',
      nuances: [
        { id: 'ember-dots', target: 'dots', colorKey: 'color6', amount: 0.2, thresholdRange: { min: 54, max: 189 }, seed: 524 },
        { id: 'ember-lines', target: 'lines', colorKey: 'color1', amount: 0.185, thresholdRange: { min: 94, max: 255 }, seed: 896 },
      ],
      seed: 775,
      imageOffsetX: 0,
      imageOffsetY: 0.08908238927414987,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 650,
          thresholdRange: { min: 33, max: 170 },
          gamma: 0.35,
          dotScale: 3.9,
          lineScale: 2.8,
          distance: 0,
          grid: true,
          routing: 'traces',
          dirAngle: 227,
          dirSpread: 108,
          traceBranch: 4,
          fill: false,
          dotOutline: false,
          dotOutlineWidth: 0.75,
          dotColorKey: 'color2',
          lineColorKey: 'color3',
          nuances: [
            { id: 'ember-sub-pop', target: 'dots', colorKey: 'color5', amount: 0.14, thresholdRange: { min: 0, max: 255 }, seed: 200 },
            { id: 'ember-sub-light', target: 'dots', colorKey: 'color1', amount: 0, thresholdRange: { min: 77, max: 255 }, seed: 717 },
            { id: 'ember-sub-warm', target: 'dots', colorKey: 'color4', amount: 0.07976943973031181, thresholdRange: { min: 150, max: 251 }, seed: 881 },
          ],
          seed: 649,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
    parentStackIndex: 1,
  },
  {
    // Exported from the app (node-preset-1782382498295): outlined trace dots with warm
    // nuances over a filled trace band. Parent renders below the sublayer.
    name: 'Clay traces',
    nodeSettings: {
      density: 2200,
      thresholdRange: { min: 0, max: 38 },
      gamma: 1.35,
      dotScale: 1.15,
      lineScale: 1.05,
      distance: 17.2,
      grid: true,
      routing: 'traces',
      dirAngle: 0,
      dirSpread: 103,
      traceBranch: 6,
      fill: false,
      dotOutline: true,
      dotOutlineWidth: 0.6,
      dotColorKey: 'color7',
      lineColorKey: 'color2',
      nuances: [
        { id: 'clay-dots-deep', target: 'dots', colorKey: 'color3', amount: 0.03285302769174503, thresholdRange: { min: 97, max: 223 }, seed: 969 },
        { id: 'clay-dots-pop', target: 'dots', colorKey: 'color2', amount: 0.06763706306159002, thresholdRange: { min: 162, max: 228 }, seed: 585 },
      ],
      seed: 961,
      imageOffsetX: 0,
      imageOffsetY: -0.09107789124259393,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 2250,
          thresholdRange: { min: 123, max: 194 },
          gamma: 1.2,
          dotScale: 1.5930745894221414,
          lineScale: 0.8746780796168905,
          distance: 14.393339010295776,
          grid: true,
          routing: 'traces',
          dirAngle: 282,
          dirSpread: 52,
          traceBranch: 6,
          fill: true,
          dotOutline: false,
          dotOutlineWidth: 0.3059043649347043,
          dotColorKey: 'color3',
          lineColorKey: 'color1',
          nuances: [
            { id: 'clay-sub-pop', target: 'dots', colorKey: 'color2', amount: 0.10516075331633423, thresholdRange: { min: 0, max: 255 }, seed: 497 },
          ],
          seed: 218,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
    parentStackIndex: 0,
  },
  {
    // Exported from the app (node-preset-1782382859734): loose free-routed dots with warm/
    // deep nuances over a directional-trace sublayer band. Parent renders above the
    // sublayer. Sublayer dots use color2 (teal) instead of the exported color3.
    name: 'Pool drift',
    nodeSettings: {
      density: 2600,
      thresholdRange: { min: 0, max: 101 },
      gamma: 1.2440803396067877,
      dotScale: 2.6,
      lineScale: 1.75,
      distance: 11.7,
      grid: false,
      routing: 'free',
      dirAngle: 141,
      dirSpread: 57,
      traceBranch: 4,
      fill: false,
      dotOutline: false,
      dotOutlineWidth: 0.2547908070330824,
      dotColorKey: 'color7',
      lineColorKey: 'color5',
      nuances: [
        { id: 'pool-dots-accent', target: 'dots', colorKey: 'color8', amount: 0.024935421344817733, thresholdRange: { min: 0, max: 255 }, seed: 740 },
        { id: 'pool-lines-deep', target: 'lines', colorKey: 'color3', amount: 0.04006987156932751, thresholdRange: { min: 10, max: 209 }, seed: 968 },
        { id: 'pool-dots-dark', target: 'dots', colorKey: 'color9', amount: 0.155, thresholdRange: { min: 12, max: 154 }, seed: 757 },
      ],
      seed: 365,
      imageOffsetX: 0,
      imageOffsetY: 0.27557261645213665,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 1600,
          thresholdRange: { min: 163, max: 180 },
          gamma: 0.9,
          dotScale: 2.35,
          lineScale: 2.2367614008563894,
          distance: 2,
          grid: true,
          routing: 'directional',
          dirAngle: 110,
          dirSpread: 126,
          traceBranch: 5,
          fill: false,
          dotOutline: true,
          dotOutlineWidth: 0.5,
          dotColorKey: 'color2',
          lineColorKey: 'color2',
          nuances: [
            { id: 'pool-sub-light', target: 'dots', colorKey: 'color7', amount: 0.2, thresholdRange: { min: 0, max: 255 }, seed: 368 },
            { id: 'pool-sub-line-bright', target: 'lines', colorKey: 'color6', amount: 0.03, thresholdRange: { min: 0, max: 255 }, seed: 270 },
            { id: 'pool-sub-line-deep', target: 'lines', colorKey: 'color5', amount: 0.065, thresholdRange: { min: 0, max: 255 }, seed: 614 },
          ],
          seed: 327,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
    parentStackIndex: 1,
  },
  {
    // Exported from the app (node-preset-1782386179539): loose free-routed dots with warm
    // dot/line nuances over a directional-grid band of big outlined dots with a light
    // highlight. Parent renders above the sublayer.
    name: 'Amber drift',
    nodeSettings: {
      density: 2600,
      thresholdRange: { min: 0, max: 101 },
      gamma: 1.2440803396067877,
      dotScale: 2.6,
      lineScale: 1.75,
      distance: 11.7,
      grid: false,
      routing: 'free',
      dirAngle: 141,
      dirSpread: 57,
      traceBranch: 4,
      fill: false,
      dotOutline: false,
      dotOutlineWidth: 0.2547908070330824,
      dotColorKey: 'color7',
      lineColorKey: 'color5',
      nuances: [
        { id: 'amber-dots-deep', target: 'dots', colorKey: 'color2', amount: 0.1297891080135472, thresholdRange: { min: 0, max: 255 }, seed: 284 },
        { id: 'amber-lines-warm', target: 'lines', colorKey: 'color4', amount: 0.06800255487951336, thresholdRange: { min: 0, max: 255 }, seed: 60 },
      ],
      seed: 870,
      imageOffsetX: 0,
      imageOffsetY: 0.1970109607549013,
    },
    nodeSubLayers: [
      {
        settings: {
          density: 1600,
          thresholdRange: { min: 145, max: 219 },
          gamma: 0.75,
          dotScale: 2,
          lineScale: 2.75,
          distance: 8.6,
          grid: true,
          routing: 'directional',
          dirAngle: 110,
          dirSpread: 126,
          traceBranch: 5,
          fill: false,
          dotOutline: true,
          dotOutlineWidth: 0.9,
          dotColorKey: 'color2',
          lineColorKey: 'color2',
          nuances: [
            { id: 'amber-sub-light', target: 'dots', colorKey: 'color1', amount: 0.165, thresholdRange: { min: 0, max: 255 }, seed: 195 },
          ],
          seed: 463,
          imageOffsetX: 0,
          imageOffsetY: 0,
        },
      },
    ],
    parentStackIndex: 1,
  },
];
